### ISSUE TITLE
keystore.password=changeit ... how to change it?

### ISSUE THREAD

**Issue by tranquility-base** [cloudcoderdotorg/CloudCoder#75]
Doing 

    java -jar cloudcoderApp-v0.0.9.jar listconfig

shows the config entry

    cloudcoder.submitsvc.ssl.keystore.password=changeit

for both the webapp and builder. Is this something that needs changing post-install? If so, how?

**Comment by daveho** [comment]
This only has to do with how the app accesses the keystore.  There's no need to change it (i.e., changing it wouldn't increase security: if the app jarfile is compromised, the contents of the keystore are compromised, because the keystore password is stored in cloudcoder.properties in the webapp jarfile.)
